### ISSUE TITLE
RabbitMQ.Client

### ISSUE THREAD

**Issue by jphamilton2** [escendit/Escendit.Orleans.Streaming.RabbitMQ#3]
Any chance you can bump RabbitMQ.Client to the latest version? 

5.2.0 is more than 10 versions back.

**Comment by jphamilton2** [comment]
I verified the behavior with a simple silo/client project using latest RabbitMQ.Client. Saw the same behavior. AMQP connection is accepted, but the handshake times out. 

In my test, I created an IConnection and registered it in ConfigureServices for the silo. I was able to then inject it into a grain where I could create a channel and publish to a queue.

Admittedly, I am not sure how this project deals with creating connections, but my thought is that a workaround would be to create a single IConnection during the configuration of the adapter somewhere and it would probably work. 

As far as I know,  it is generally recommended that a process maintain a long-lived connection and reuse it. So maybe, this is a way forward? I will try to put something together by the end of the weekend. BUT I have never used the streaming aspect of Rabbit so I may be way off base here.

**Comment by snovak7** [comment]
I currently use two long lived connections, one for publishing and one for consuming. It is rather done statically, so there is room for improvement.

I was thinking of implementing named configuration, but it felt too time consuming at the moment.

You're welcome to contribute of course.

I personally am more inclined to the use of Streams, sadly infinite storage doesn't exist. 🥲

**Comment by jphamilton2** [comment]
To be more clear, in my test I discovered that everything seemed to work if I built IConnection during the configuration of the silo, so before:

```
var host = builder.Build();
```

You are building the connections during the Build. I don't know why this matters but it does. Also, I don't know if it's worth exploring this further, because it seems like it would be a major change to create the actual Rabbit connections during the configuration steps. But if you say go for it, I will give it a try.

**Comment by snovak7** [comment]
I don't like this, this would mean that the startup could fail while connecting during configuration.

I've seen similar pattern though in "StackExchange.Redis".

Can you look [this example](https://gist.github.com/snovak7/f9efcbcc36640e37a05a9b0d2dd433c9), what happens if you do

```c#
.UseOrleans(...)
.RunConsoleAsync()
```

Running as a Console Application?

Here is the implementation:
https://github.com/dotnet/runtime/blob/15d7761208c88c4bcd2c5052cbccc25f26b5a8a4/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L364-L377

Also Orleans has this `IQueueAdapterFactory` which you need to implement and is run at some point after Orleans initializes.

https://github.com/escendit/Escendit.Orleans.Streaming.RabbitMQ/blob/79c6b27cb78b0568b384b9faa08f2d1eec5de446/src/Escendit.Orleans.Streaming.RabbitMQ/Queue/DefaultQueueAdapterFactory.cs#L143-L155

The possible solution then it would be to prepare connection(s) and put it into service provider as named service, then factory should fetch the named service and get connections and put to use.

**Comment by snovak7** [comment]
I've played with this a little.

Introduced named factories

```c#
services
  .AddSingletonNamedService<IConnectionFactory>(
    name,
    (serviceProvider, providerName) =>
    {
        var options = serviceProvider.GetOptionsByName<RabbitQueueOptions>(providerName);
        return new ConnectionFactory { ... }                   
    },
  };
})
```

Introduced new class which holds two connections with Producer & Consumer (still try to name it properly)

```c#
services
  .AddSingletonNamedService<IQueueBus>(
    name,
    (serviceProvider, providerName) =>
    {
      var options = serviceProvider.GetOptionsByName<RabbitQueueOptions>(providerName);
      var connectionFactory = serviceProvider.GetRequiredServiceByName<IConnectionFactory>(providerName);

      var producerConnection = Task
        .Run(
          () => connectionFactory.CreateConnection(...))
        .ConfigureAwait(false)
        .GetAwaiter()
        .GetResult();
  
        var consumerConnection = Task
          .Run(
            () => connectionFactory.CreateConnection(...))
          .ConfigureAwait(false)
          .GetAwaiter()
          .GetResult();
  
        return new DefaultQueueBus(name, producer, consumer);
    });
```

If I wrap with `Task.Run` with `.ConfigureAwait(false)` this starts working, since it is a good practice to use `TaskScheduler.Default` in libraries. Also checked with Orleans teams, so I guess I will implement this for the newer version of RabbitMQ.Client

**Comment by jphamilton** [comment]
I've been working with this, too and discovered the exact same thing. MassTransit works fine in Orleans so I dug through that codebase and saw they were wrapping connection creation with Task.Run. I have it working with all queue related tests passing. But I have never been able to get the streaming aspects of this library to work, so I don't know about that.

Another issue that I noticed that <code>RabbitOptionsBase.TotalQueueCount</code> is 8 by default. This is creating 8 connections, 8 exchanges and 8 queues. To me this is a little excessive. I think this could be done with 1 connection, 1 exchange and 8 queues and bring routing with streamId into it. This is just a gut feeling because I am not really sure how things need to be hooked up to satisfy Orleans.

**Comment by jphamilton** [comment]
In your example, you could accomplish that with one IConnection and two IModel (one for producer, one for consumer).

**Comment by snovak7** [comment]
The `TotalQueueCount` was copied from the Orleans `HashRingStreamQueueMapperOptions`.

I guess 1 connection would be good choice, would simplify design, it would minimize resources, I agree on one model for publisher, since there's not much to do to send the data. I am not sure about consumers, since it is mimicking streaming, queues are partitioned. This is mostly environment for streaming inside of Orleans Clusters, not to mention receivers have

For exchanges now queueId is generated and used as a exchange name which has the same name as queue. This was simplest for me at the time, I understand rabbitmq better now, using only one exchange is maybe a little easier to handle.

I will see what I can do!

**Comment by jphamilton** [comment]
Nice, looking forward to seeing what you come up. Personally, I'm an Orleans noob but I hope to help out once I come up to speed with it.

**Comment by snovak7** [comment]
I merged the changes, check it out!

**Comment by jphamilton** [comment]
Right on! Have only casually looked at parts of the code I know, but this just seems like a big step forward. Like the direction a lot. I'm going to dive in more tonight. I ran my sample and the Rabbit topology is way closer to what I would expect.
